### ISSUE TITLE
Settings.json Permissions

### ISSUE THREAD

**Issue by stukinnear** [RaunoT/plex-rewind#104]
### Plex Rewind Version

1.87

### Description

What permissions need to be on the settings.json file?

As I get the following error:

Something went wrong!

When I try to save after running http://localhost:8383

### Steps to reproduce

After loading http://localhost:8383 - entering details - then trying to save.

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser and version

Edge Version 126.0.2592.87 (Official build) (64-bit)

**Comment by stukinnear** [comment]
Chmod 777 - clicked save - chmod 665

**Comment by nwithan8** [comment]
Not complete, the Docker container should auto-generate a settings.json file with the proper permissions if one does not already exist, rather than requiring the user to create one (likely creating one with the host user rather than the Docker user, and therefore with the wrong permissions)

**Comment by RaunoT** [comment]
> Not complete, the Docker container should auto-generate a settings.json file with the proper permissions if one does not already exist, rather than requiring the user to create one (likely creating one with the host user rather than the Docker user, and therefore with the wrong permissions)

A settings file is now infact automatically generated, if it doesn't exist already, as per [5d69ca9](https://github.com/RaunoT/plex-rewind/commit/5d69ca946da11455ebdf665071317534b6dc76ea). 
Please open a new issue if relevant.

**Comment by jl94x4** [comment]
I'm having a similar permissions error, its saying it cannot create one.

**Comment by jl94x4** [comment]
`  ▲ Next.js 14.2.5


  - Local:        http://localhost:8383


  - Network:      http://0.0.0.0:8383




 ✓ Starting...


 ✓ Ready in 107ms


Error writing settings file! Error: EACCES: permission denied, open '/app/config/settings.json'


    at async open (node:internal/fs/promises:639:25)


    at async Object.writeFile (node:internal/fs/promises:1219:14)


    at async d (/app/.next/server/app/settings/connection/page.js:1:9787)


    at async /app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418


    at async rR (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978)


    at async r7 (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1144)


    at async doRender (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1438:30)


    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)


    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)


    at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1931:24) {


  errno: -13,


  code: 'EACCES',


  syscall: 'open',


  path: '/app/config/settings.json'


}


Error writing settings file! Error: EACCES: permission denied, open '/app/config/settings.json'


    at async open (node:internal/fs/promises:639:25)


    at async Object.writeFile (node:internal/fs/promises:1219:14)


    at async d (/app/.next/server/app/settings/connection/page.js:1:9787)


    at async /app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418


    at async rR (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978)


    at async r7 (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1144)


    at async doRender (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1438:30)


    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)


    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)


    at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1931:24) {


  errno: -13,


  code: 'EACCES',


  syscall: 'open',


  path: '/app/config/settings.json'`

**Comment by RaunoT** [comment]
@jl94x4 probably related to #144.
I suggest moving discussion there as this issue is closed.
