### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by stukinnear** [RaunoT/plex-rewind#126]
### Plex Rewind Version

2.0.1

### Description

I have multiple libraries on my Plex but when I click on a 2 of them I get 

"Uh oh.. something went wrong!"

Log output below.

### Steps to reproduce

Dashboard
Select library
Uh oh.. something went wrong!

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'id')
    at /app/.next/server/app/dashboard/[slug]/page.js:1:7345
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async i (/app/.next/server/app/dashboard/[slug]/page.js:1:7115)
    at async o (/app/.next/server/app/dashboard/[slug]/page.js:1:4760)
    at async Promise.all (index 0)
    at async h (/app/.next/server/app/dashboard/[slug]/page.js:1:6055) {
  digest: '2393337188'
```

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser and version

Edge Version 126.0.2592.87 (Official build) (64-bit)

**Comment by cdnutter** [comment]
Same issue as above.

Tautulli, Overseerr, and TMDB all linked.
It can read the libraries it just won't work with more than 1 library detected.
I'm assuming support is included for more than 1 library as it has a response for both Movies & TV shows watched.

Would love to see a fix.

**Comment by stukinnear** [comment]
I updated the image to 2.0.3 - same error.

Really appreciate your efforts Rauno.

**Comment by RaunoT** [comment]
@stukinnear @cdnutter could you please assist me in testing `ghcr.io/raunot/plex-rewind:8b7722475bdf3df490ca27352f7b5e385d2a4ad1` as a potential fix for this? You can set this as the image in docker-compose and run `docker compose pull` and then `docker compose up -d` 🙏

**Comment by stukinnear** [comment]
Done.

Same issue.

Here's the Overseerr user.id undefined
Here's the Overseerr user.id 6
Here's the Overseerr user.id 1
Here's the Overseerr user.id undefined
Here's the Overseerr user.id 2
Here's the Overseerr user.id 3
TypeError: Cannot read properties of undefined (reading 'id')
    at /app/.next/server/app/dashboard/[slug]/page.js:1:7345
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async i (/app/.next/server/app/dashboard/[slug]/page.js:1:7115)
    at async o (/app/.next/server/app/dashboard/[slug]/page.js:1:4760)
    at async Promise.all (index 0)
    at async h (/app/.next/server/app/dashboard/[slug]/page.js:1:6055) {
  digest: '1934029383'
}
Fetched tmdbId 1245673
Fetched tmdbId 1086805
Fetched tmdbId 491592
Fetched tmdbId 1263766

**Comment by RaunoT** [comment]
@stukinnear could you please try removing both OVERSEERR URL and OVERSEERR API KEY from settings and re-saving? Just trying to see if this behavior can be reproduced without Overseerr active.

**Comment by stukinnear** [comment]
Same problem I am afraid.

TypeError: Cannot read properties of undefined (reading 'id')
    at /app/.next/server/app/dashboard/[slug]/page.js:1:7345
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async i (/app/.next/server/app/dashboard/[slug]/page.js:1:7115)
    at async o (/app/.next/server/app/dashboard/[slug]/page.js:1:4760)
    at async Promise.all (index 0)
    at async h (/app/.next/server/app/dashboard/[slug]/page.js:1:6055) {
  digest: '2393337188'
}
Fetched tmdbId 491592
Fetched tmdbId 1086805
Fetched tmdbId 1263766
Fetched tmdbId 1245673

**Comment by stukinnear** [comment]
I have 5 libraries - two that use the Film library type - Documentaries and Films and three that use TV Programmes library type - Drama. Comedy & Factual TV.

The two that throw up the error are:

Documentaries and Drama.

**Comment by cdnutter** [comment]
> @stukinnear @cdnutter could you please assist me in testing `ghcr.io/raunot/plex-rewind:8b7722475bdf3df490ca27352f7b5e385d2a4ad1` as a potential fix for this? 🙏 You can set this as the image in docker-compose and run `docker compose pull` and then `docker compose up -d`

Same issue as @stukinnear. 

`TypeError: Cannot read properties of undefined (reading 'id')
    at /app/.next/server/app/rewind/page.js:1:40785
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async a (/app/.next/server/app/rewind/page.js:1:40555)
    at async h (/app/.next/server/app/rewind/page.js:1:35776)
    at async Promise.all (index 0)
    at async _ (/app/.next/server/app/rewind/page.js:1:36971) {
  digest: '517408798'
}`

I've also removed Overseerr and same issue.
I have 15 libraries. I enabled around 6 and the issue happened.
After digging through I disabled and enabled ones that did and didn't work.
The only one that DIDN'T work was 4K TV Shows. 

The library section ID for that is 3.

Hopefully that can help you out.

**Comment by cdnutter** [comment]
> `ghcr.io/raunot/plex-rewind:19d5cc1d0b9620558f8a034d6a58ccac7c453f7d`

This worked! I've enabled the all the libraries I use and it goes through.

**Comment by stukinnear** [comment]
It works - outstanding effort Rauno.

Really appreciate this.

**Comment by stukinnear** [comment]
I re-enabled the Overseer stuff and it still works.
