### ISSUE TITLE
Gettng error at plex log in. 

### ISSUE THREAD

**Issue by dags170291** [RaunoT/plex-rewind#181]
### Plex Rewind Version

2.3.1

### Description

Getting "were unable to complete this request"  

### Steps to reproduce

1. Happens after entering API keys

### Screenshots

![Arc 20240725-122927](https://github.com/user-attachments/assets/4bbd2137-4094-47a6-b48b-716cc502f288)

### Logs

```shell
▲ Next.js 14.2.5
  - Local:        http://localhost:8383
  - Network:      http://0.0.0.0:8383
 ✓ Starting...
 ✓ Ready in 96ms
Error testing TMDB connection! TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async d (/app/.next/server/app/settings/connection/page.js:1:8283)
    at async /app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
    at async rR (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978)
    at async r7 (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1144)
    at async doRender (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)
    at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1931:24) {
  [cause]: Error: getaddrinfo EAI_AGAIN api.themoviedb.org
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
      at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'api.themoviedb.org'
  }
}
```

### Platform

desktop

### Device

Desktop Server

### Operating System

UBUNTU via Docker

### Browser and version

ARC browser

**Comment by RaunoT** [comment]
I take it from your Reddit comment that the issue is solved and can be closed? 🙏
