### ISSUE TITLE
Not Showing Libraries

### ISSUE THREAD

**Issue by havocmaster** [RaunoT/plex-rewind#191]
### Plex Rewind Version

2.3.1

### Description

I am unable to see more then just the users on my dashboard, none of my libraries are showing.

### Steps to reproduce

None.

### Screenshots

![dashboard](https://github.com/user-attachments/assets/890dae6d-4657-4f8e-9d38-d738c509778b)

### Logs

```shell
2024-07-27 15:16:55.320812-04:00▲ Next.js 14.2.5
2024-07-27 15:16:55.320930-04:00- Local:        http://localhost:8383
2024-07-27 15:16:55.320948-04:00- Network:      http://0.0.0.0:8383
2024-07-27 15:16:55.320981-04:002024-07-27T15:16:55.320981593-04:00
2024-07-27 15:16:55.321039-04:00✓ Starting...
2024-07-27 15:16:55.357599-04:00✓ Ready in 41ms
2024-07-27 15:17:22.571248-04:00Overseerr URL is not configured! Skipping request.
2024-07-27 15:17:41.764136-04:002024-07-27T15:17:41.764136811-04:00
2024-07-27 15:17:41.764182-04:00(process:1): VIPS-WARNING **: 19:17:41.764: threads clipped to 1024
2024-07-27 15:17:46.528104-04:00Overseerr URL is not configured! Skipping request.
2024-07-27 15:17:52.994906-04:00Overseerr URL is not configured! Skipping request.
```

### Platform

desktop

### Device

Truenas

### Operating System

Truenas Scale Dragonfish-24.04.2

### Browser and version

Any

**Comment by RaunoT** [comment]
Have you enabled any libraries under Settings -> Features?

**Comment by havocmaster** [comment]
Sorry, I must be blind but I'm not seeing any Settings button.
Once logged in I only have "Start Rewind", "Dashboard" and "Sign Out".

What did I mess up?

**Comment by RaunoT** [comment]
Is the account you used to sign in an admin of the Plex server? After the initial setup, a user must be an admin to edit settings.

**Comment by havocmaster** [comment]
Yes, I'm the admin:

![user](https://github.com/user-attachments/assets/d6aeea51-1084-4218-80dc-6c40999f0316)

**Comment by RaunoT** [comment]
Im assuming you don't see a settings cog at the top right of the page?

![image](https://github.com/user-attachments/assets/00a469c0-7de2-4c37-a783-992fd4f43bb4)

And when you try manually going to `/settings/features`, you are redirected back to the homepage?

Could you please try logging in and out once more and seeing if the issue persists?

There is currently no way to alter the debug level. Might be a good idea to add in the future though.

**Comment by havocmaster** [comment]
No cogs, the `/settings/features` does redirect to the homepage, and I tried the develop branch and get the same thing.
Also tried deleting the config file to start fresh, still no luck.

**Comment by hunterwinterton** [comment]
I'm having the same issue... None of my libraries show up, and I can't access the settings page even though I am the owner of the Plex server.

**Comment by RaunoT** [comment]
Please try the latest `develop` image again. It should now have more verbose logging in the server, specifically for whether the user is picked up as an admin and if any libraries are returned.

**Comment by havocmaster** [comment]
I just tried 2.5.0-develop.7

When I load the page, instead of bringing me to the homepage it tries to open `/settings/connection`, which gives a "too many redirect" error and won't even load up anything:

![image](https://github.com/user-attachments/assets/d3d75a0d-f324-4160-8627-dfc1978f96ec)

Not getting anything reported in the logs:

```
2024-07-30 07:41:47.602223-04:00▲ Next.js 14.2.5
2024-07-30 07:41:47.602380-04:00- Local:        http://localhost:8383
2024-07-30 07:41:47.602463-04:00- Network:      http://0.0.0.0:8383
2024-07-30 07:41:47.602503-04:002024-07-30T07:41:47.602503850-04:00
2024-07-30 07:41:47.602534-04:00✓ Starting...
2024-07-30 07:41:47.639831-04:00✓ Ready in 41ms

```

**Comment by RaunoT** [comment]
Apologies, thanks for catching that. Should be fixed now in `2.5.0-develop.8`.

**Comment by havocmaster** [comment]
According to the logs I'm not recognized as the admin.

```
2024-07-30 08:49:38.022161-04:00▲ Next.js 14.2.5
2024-07-30 08:49:38.022344-04:00- Local:        http://localhost:8383
2024-07-30 08:49:38.022439-04:00- Network:      http://0.0.0.0:8383
2024-07-30 08:49:38.022493-04:002024-07-30T08:49:38.022493581-04:00
2024-07-30 08:49:38.022516-04:00✓ Starting...
2024-07-30 08:49:38.057423-04:00✓ Ready in 39ms
2024-07-30 08:51:08.790985-04:002024-07-30T08:51:08.790985489-04:00
2024-07-30 08:51:08.791014-04:00(process:1): VIPS-WARNING **: 12:51:08.790: threads clipped to 1024
2024-07-30 08:51:15.493843-04:00[AUTH] - User logged in with data: {
2024-07-30 08:51:15.493894-04:00id: '1234567',
2024-07-30 08:51:15.493900-04:00name: 'havocmasterz',
2024-07-30 08:51:15.493904-04:00email: '**************@yahoo.ca',
2024-07-30 08:51:15.493908-04:00image: 'https://plex.tv/users/53960d76329c52ea/avatar?c=1722343874',
2024-07-30 08:51:15.495892-04:00isAdmin: false
2024-07-30 08:51:15.495930-04:00}

```

**Comment by RaunoT** [comment]
That's curious, as that info is fetched straight from the Plex API. 
Specifically, it's looking for the `homeAdmin` have a value of 1 for the admin.

I've created a separate image to debug this further. Please try installing the image following image:
`ghcr.io/raunot/plex-rewind:6374ba98f9a126632a1cb2db66a4fc839a8c42ee` and signing in and out again. You should then be able to see the full user info call URL to Plex API with your personal X-Plex-Token. Go to that link and inspect the .xml. Don't share the token.

Example: `https://plex.tv/api/v2/user?X-Plex-Token=your-token-here`

It should contain `homeAdmin="1"`, also make sure the `email` and `username` match up between the login for Plex Rewind and the home admin account. Another good indicator if that is the correct account with the correct access, is `homeSize`, which should match the count of users on your server.

**Comment by havocmaster** [comment]
ok, this was very usefull, I was able to get it working.
homeSize=1 but homeAdmin=0.
I enabled the guest user and now I get homeSize=1 and homeAdmin=1.

I now have access to the settings.

Conclusion is that it will return homeadmin=1 if you have more then 1 home user.  If you are the only user homeadmin=0.

**Comment by cliffordwhansen** [comment]
I can confirm the above, I only have 1 home user
```
home="0" guest="0" homeSize="1" homeAdmin="0" maxHomeSize="15"
```

I enabled guest access and then
```
home="1" guest="0" homeSize="1" homeAdmin="1"
```

Logged out of rewind and back in and now can edit settings, I updated my settings and then disabled the guest user again.

**Comment by havocmaster** [comment]
I can live with that, I will enable/disable the guest user whenever I need to change settings.

Thanks RaunoT!

**Comment by RaunoT** [comment]
Thanks for testing! No more need for guest user now!

**Comment by RaunoT** [comment]
Unfortunately this change has opened another issue #212.
I have made additional adjustments in #213 and the following image:
`ghcr.io/raunot/plex-rewind:35510f63984e45f630452ac019aef3e520dcb9a1`

@cliffordwhansen and @havocmaster I'd be grateful, if you could please check that image and confirm everything still works as expected for you.

**Comment by havocmaster** [comment]
Tried ` ghcr.io/raunot/plex-rewind:35510f63984e45f630452ac019aef3e520dcb9a1`, still works as expected 👍

**Comment by cliffordwhansen** [comment]
@RaunoT When I take out the `user: 1000:1000` it works as expected and I get the following
```
plex-rewind  | [AUTH] - User logged in with data: {
plex-rewind  |   id: 'xxx',
plex-rewind  |   name: 'Clifford W. Hansen',
plex-rewind  |   email: 'xxxx',
plex-rewind  |   image: 'https://plex.tv/users/xxxx/avatar?c=xxx',
plex-rewind  |   isAdmin: true
plex-rewind  | }
```

When I specify `user: 1000:1000` I get a bunch of these (not serious everything still works):
```
plex-rewind  | Failed to update prerender cache for 67f52747d4e0777b02f59624d710f2d8352ec070aae88f906d476c265b5d23af Error: EACCES: permission denied, mkdir '/app/.next/cache'
plex-rewind  |     at async Object.mkdir (node:internal/fs/promises:858:10)
plex-rewind  |     at async FileSystemCache.set (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/incremental-cache/file-system-cache.js:276:13)
plex-rewind  |     at async IncrementalCache.set (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/incremental-cache/index.js:411:13)
plex-rewind  |     at async /app/.next/server/chunks/357.js:2:7073
plex-rewind  |     at async u (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:5826)
plex-rewind  |     at async c (/app/.next/server/app/api/auth/[...nextauth]/route.js:3:99)
plex-rewind  |     at async Promise.all (index 5)
plex-rewind  |     at async P (/app/.next/server/app/rewind/page.js:1:42008) {
plex-rewind  |   errno: -13,
plex-rewind  |   code: 'EACCES',
plex-rewind  |   syscall: 'mkdir',
plex-rewind  |   path: '/app/.next/cache'
plex-rewind  | }
```

I did remove the image and containers between runs

**Comment by RaunoT** [comment]
Thanks both!

**Comment by havocmaster** [comment]
I can confirm, I get the same thing in the logs when I run as user 1004:1004, but the webpage shows no issues and displays stats as expected.

`2024-08-06T09:58:23.731216656-04:00 Failed to update prerender cache for ce0106589a3510d5d8a188123ccde036136f286247b65fe2c34330a115886217 Error: EACCES: permission denied, mkdir '/app/.next/cache'
2024-08-06T09:58:23.731365763-04:00     at async Object.mkdir (node:internal/fs/promises:858:10)
2024-08-06T09:58:23.731390535-04:00     at async FileSystemCache.set (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/incremental-cache/file-system-cache.js:276:13)
2024-08-06T09:58:23.731509093-04:00     at async IncrementalCache.set (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/incremental-cache/index.js:411:13)
2024-08-06T09:58:23.731553925-04:00     at async /app/.next/server/chunks/357.js:2:7073
2024-08-06T09:58:23.731565506-04:00     at async u (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:5826)
2024-08-06T09:58:23.731575219-04:00     at async c (/app/.next/server/app/api/auth/[...nextauth]/route.js:3:99)
2024-08-06T09:58:23.731585372-04:00     at async Promise.all (index 3)
2024-08-06T09:58:23.731602080-04:00     at async y (/app/.next/server/app/dashboard/[slug]/page.js:1:6360) {
2024-08-06T09:58:23.731612201-04:00   errno: -13,
2024-08-06T09:58:23.731621982-04:00   code: 'EACCES',
2024-08-06T09:58:23.731631524-04:00   syscall: 'mkdir',
2024-08-06T09:58:23.731657819-04:00   path: '/app/.next/cache'
2024-08-06T09:58:23.731686424-04:00 }
`
