### ISSUE TITLE
500 server error through public proxy

### ISSUE THREAD

**Issue by lordtaco** [RaunoT/plex-rewind#274]
### Plex Rewind Version

4.4.3

### Description

I love this a lot, and I got it to work for a little bit, but after rebooting the server, I've run into an issue. When I set `NEXTAUTH_URL` and `NEXTAUTH_PUBLIC_SITE_URL` to my reverse proxy URL, I get a 500 server error.

If I change it back to the local IP, I can access it that way perfectly and it works through the reverse proxy, but I can't authenticate with Plex because I think it's still trying to use the private IP URL for the callback.

I have now tried this on two different servers and get the same result both times. It really doesn't like something with my reverse proxy. I've tried with both SSL on and off in nginx.

My nginx conf:
```
server {
    listen 80;
    server_name rewind.tacoplex.space;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name rewind.tacoplex.space;

    ssl_certificate /etc/letsencrypt/live/tacoplex.space/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tacoplex.space/privkey.pem;

    location /.well-known/ {
        root /var/www/html;
    }

    location / {
        proxy_pass http://172.16.1.19:8383;

        # Forward headers (move them here)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Ssl on;

        # Other settings for proxy
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off; # Disable buffering for streaming
    }
}
```

### Steps to reproduce

docker-compose.yml (working but only on my local network):
```services:
  plex-rewind:
    image: ghcr.io/raunot/plex-rewind:latest # :develop for the latest development version
    container_name: plex-rewind
    environment:
      - NEXTAUTH_SECRET=qjSpZAX7S8OrQBYXmY1OgMRSYZKclqCtH/5Q20MatJc= # (required) used to encrypt auth JWT token, generate one with `openssl rand -base64 32`
      - NEXTAUTH_URL=http://172.16.1.19:8383 # (required) change to your domain if you are exposing the app to the internet
      - NEXT_PUBLIC_SITE_URL=http://172.16.1.19:8383 # (required) change to your domain if you are exposing the app to the internet
    volumes:
      - ./config:/app/config
    ports:
      - 8383:8383
    restart: unless-stopped
```
When I update this file to include my public URL and then run `docker compose up --build -d`, I get the 500 internal server error.

### Screenshots

<img width="1440" alt="Screenshot 2024-11-26 at 11 20 58 PM" src="https://github.com/user-attachments/assets/a07616ff-2a57-43e5-910e-7af66be69520">

### Logs

```shell
plex-rewind  | Error: fetch failed
plex-rewind  |     at context.fetch (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/context.js:296:38)
plex-rewind  |     at Z.callbacks.authorized (/app/.next/server/src/middleware.js:2:10562)
plex-rewind  |     at /app/.next/server/src/middleware.js:3:889
plex-rewind  |     at l (/app/.next/server/src/middleware.js:3:579)
plex-rewind  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
plex-rewind  |     at async Object.t [as handler] (/app/.next/server/src/middleware.js:3:834)
plex-rewind  |     at async F (/app/.next/server/src/middleware.js:2:8414)
plex-rewind  |     at async /app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22
plex-rewind  |     at async runWithTaggedErrors (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)
plex-rewind  |     at async NextNodeServer.runMiddleware (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:1062:24) {
plex-rewind  |   cause: ConnectTimeoutError: Connect Timeout Error
plex-rewind  |       at onConnectTimeout (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:9145:28)
plex-rewind  |       at eval (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:9101:50)
plex-rewind  |       at Immediate.eval [as _onImmediate] (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:9133:13)
plex-rewind  |       at process.processImmediate (node:internal/timers:483:21)
plex-rewind  |       at process.callbackTrampoline (node:internal/async_hooks:130:17) {
plex-rewind  |     code: 'UND_ERR_CONNECT_TIMEOUT'
plex-rewind  |   }
plex-rewind  | }
```

### Platform

desktop

### Device

Ubuntu Server

### Operating System

Ubuntu 22.04.5 LTS

### Browser and version

Chrome 131.0.6778.86

**Comment by lordtaco** [comment]
Not running UFW on either the proxy or the server either, networking-wise nothing should be blocked/filtered.

**Comment by RaunoT** [comment]
A `ConnectTimeoutError` fetch error in middleware indicates that `/api/missing-setting` is being blocked, since that's the only fetch running there. Since the project is working for you locally, the issue must lie in your reverse proxy setup. 

Wish I could help you more, but unfortunately I'm not an expert on reverse proxy configs and this is beyond the scope of the project itself. For what it's worth, I personally use [nginx proxy manager](https://github.com/NginxProxyManager/nginx-proxy-manager) in my setup.
