### ISSUE TITLE
Tautulli 500 error

### ISSUE THREAD

**Issue by elit3ge** [RaunoT/plex-rewind#93]
### Plex Rewind Version

v1.8.7

### Description

Upon authenticating and then clicking on Rewind "Uh oh.. something went wrong!" error appears.

### Steps to reproduce

Spinup a docker compose

### Screenshots

![image](https://github.com/RaunoT/plex-rewind/assets/1644699/3e45726a-f42c-4949-8036-48e74f81c9dc)

### Logs

```shell
▲ Next.js 14.0.4

   - Local:        http://localhost:8383

   - Network:      http://0.0.0.0:8383

 ✓ Ready in 59ms

Error fetching from Tautulli API. The query was 'get_library_media_info'.

 Error: Tautulli API request failed: 500 Internal Server Error

    at s (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:6117)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async c (/app/.next/server/app/dashboard/(route)/[slug]/page.js:1:6348)

    at async Promise.all (index 2)

    at async f (/app/.next/server/app/dashboard/(route)/[slug]/page.js:1:6955)

Error: Tautulli API request failed: 500 Internal Server Error

    at s (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:6117)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async c (/app/.next/server/app/dashboard/(route)/[slug]/page.js:1:6348)

    at async Promise.all (index 2)

    at async f (/app/.next/server/app/dashboard/(route)/[slug]/page.js:1:6955)

Error fetching from Tautulli API. The query was 'get_library_media_info'.

 Error: Tautulli API request failed: 500 Internal Server Error

    at s (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:6117)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Promise.all (index 5)

    at async d (/app/.next/server/app/rewind/page.js:1:31575)

    at async Promise.all (index 3)

    at async g (/app/.next/server/app/rewind/page.js:1:33498)

Error: Tautulli API request failed: 500 Internal Server Error

    at s (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:6117)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Promise.all (index 5)

    at async d (/app/.next/server/app/rewind/page.js:1:31575)

    at async Promise.all (index 3)

    at async g (/app/.next/server/app/rewind/page.js:1:33498)

Error fetching from Tautulli API. The query was 'get_library_media_info'.

 Error: Tautulli API request failed: 500 Internal Server Error

    at s (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:6117)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Promise.all (index 0)

Error fetching from Tautulli API. The query was 'get_library_media_info'.

 Error: Tautulli API request failed: 500 Internal Server Error

    at s (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:6117)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Promise.all (index 2)

Error fetching from Tautulli API. The query was 'get_library_media_info'.

 Error: Tautulli API request failed: 500 Internal Server Error

    at s (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:6117)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Promise.all (index 4)
```

### Platform

desktop

### Device

Desktop

### Operating System

Windows 10

### Browser and version

Firefox 121.0.1 (64-bit)

### Additional context

![image](https://github.com/RaunoT/plex-rewind/assets/1644699/f75f70da-7a33-407d-a87e-b5e5f5b08377)

**Comment by RaunoT** [comment]
Hello @elit3ge 👋 

I've just published a `2.0.0` version of `plex-rewind`. 
Since this issue deals with parts of the code that have been completely refactored, I will close this issue for now and suggest you attempt updating.

If you still run into any issues, feel free to open a new ticket.
